fromLion99/projectgroep3

- cinema/Movie.cs
- cinema/Program.cs
- cinema/Room.cs
Functies in classes geplaatst waardoor de code overzichtelijker word.
> Classes and Functions

- cinema/Movie.cs
- cinema/Program.cs
> Roby's takkie

- cinema/Program.cs
- cinema/Search.cs
Als je een verkeerde film heb toegevoegd gaat het programma terug naar het begin.
> Search function version 2

- cinema/Movie.cs
- cinema/Program.cs
- cinema/Room.cs
Function editMovie() added in the movie class. And text addded at ervery ad function that the action successfully is finished.
> editMovie() added and more

- cinema/Movie.cs
> Updated movie.cs

- cinema/Program.cs
- cinema/Search.cs
> Search function version 3.

- cinema/Movie.cs
- cinema/Program.cs
- cinema/Room.cs
- cinema/rooms.json
Added the deleteRoom(). Upgraded deleteMovie().
> Added deleteRoom and more

- .gitignore
- cinema/cinema.sln
> Gitignore updated

- cinema/.vs/cinema/xs/UserPrefs.xml
> Korneel's branchiosaurus

- cinema/Reservation.cs
- cinema/Search.cs
Je kan nu kiezen welke room je een film wilt kijken.
> Reservation function version 2

- cinema/Login.cs
- cinema/Program.cs
Accesable CRUD employee
Bug fixes in signIn(), still bugs in Login class
> Many changes

- cinema/Login.cs
> Else statements added

- cinema/Program.cs
The function startscreen is now static.
> Program.cs updated

- cinema/Employee.cs
> ViewSalesEmployee 1

- cinema/Employee.cs
- cinema/Login.cs
- cinema/Reservation.cs
- cinema/reservation.json
kleine aanpassingen aan viewsalesemployee en reservation
> Kleine aanpassingen

- cinema/Employee.cs
- cinema/Program.cs
Je kan nu ook de sales zien van een gekozen film
> viewsalesemployee update

- cinema/Employee.cs
- cinema/Program.cs
- cinema/Search.cs
viewsales is toegevoegd aan program.cs, kleine bugfix in search.cs
> viewsalesemployee 3, bugfix

- cinema/Reservation.cs
klein begin aan payReservation
> payReservation 1ste versie

- cinema/Search.cs
> code convention in search.cs

- cinema/Program.cs
Program.cs is shorter because the using of the switch statement.
> Updated Program.cs

- cinema/Login.cs
- cinema/Program.cs
- cinema/newProgram.cs
> New Program.cs

- cinema/Drink.cs
Drinks.cs is error free right now.
> Drinks error free

- cinema/Drinks.json
> Drinks.Json update

- cinema/Drinks.json
- cinema/Snacks.cs
- cinema/Snacks.json
> Errors snack.cs fixed

- cinema/Employee.cs
- cinema/Login.json
- cinema/Program.cs
de prijs word nog keer de stoelen gedaan en getoond, nog niet af
> viewsalesemployee small bugfix

- cinema/Login.json
- cinema/Search.cs
- cinema/bin/Debug/netcoreapp3.1/Login.json
je kan nu b invoeren om terug naar menu te gaan
> search.cs update
